spring.application.name=workflow-service-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_service
spring.datasource.username=postgres
spring.datasource.password=bharath
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# API Key for /api/events
app.security.api-key=your-super-secret-api-key

# JWT
app.security.jwt-secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_32+_CHARS
app.security.jwt-exp-minutes=120